#include "stage_b_rt.h"
#include <stdint.h>
#include <stdio.h>
#include <string.h>
static uint32_t q=0x56b80c55u;static uint32_t ru(void){q=q*1664525u+1013904223u;return q;}static float rf(float a,float b){return a+(b-a)*(float)(ru()>>8)*(1.0f/16777216.0f);}static uint64_t hh(uint64_t h,const void*p,size_t n){const unsigned char*b=p;for(size_t i=0;i<n;i++){h^=b[i];h*=1099511628211ULL;}return h;}
int main(void){static const uint32_t ends[20]={2,4,5,7,10,12,14,15,17,18,20,22,24,27,30,34,40,46,54,77};uint64_t h=1469598103934665603ULL;
for(unsigned t=0;t<3000;t++){
 float obj[2][4][160],*vec[2][4],**grp[2]={vec[0],vec[1]};for(unsigned r=0;r<2;r++)for(unsigned b=0;b<4;b++){vec[r][b]=obj[r][b];for(unsigned i=0;i<160;i++)obj[r][b][i]=rf(-.2f,.2f);}UbigStageBRtComplexGroups groups={2,4,grp};
 float ai[2][20],ao[2][20],*aip[2]={ai[0],ai[1]},*aop[2]={ao[0],ao[1]};for(unsigned r=0;r<2;r++)for(unsigned i=0;i<20;i++){ai[r][i]=rf(-1,0);ao[r][i]=rf(-1,0);}UbigStageBRtBandRows analysis={2,20,aip,20},output={2,20,aop,20};
 float weights[20],lower[20],upper[20],linked[20];int32_t status[20],bm[20],om[20];for(unsigned i=0;i<20;i++){weights[i]=rf(-.5f,.5f);lower[i]=rf(-1,1);upper[i]=rf(-1,1);status[i]=(int32_t)(ru()&1u);linked[i]=rf(-.5f,.5f);bm[i]=(int32_t)ru();om[i]=(int32_t)ru();}
 UbigStageBRtDeepControllerConfig dc={0};dc.active_width=20;dc.pair_bounds=(UbigStageBRtPairBoundsConfig){rf(-.3f,.3f),rf(-.3f,.3f),rf(.1f,.9f),rf(.1f,.9f)};dc.dual_envelope=(UbigStageBRtDualEnvelopeConfig){rf(-.3f,0),rf(.1f,1),rf(.1f,1),rf(.01f,.2f),rf(-.1f,.1f),rf(-.3f,0),rf(.1f,1),rf(.1f,1),rf(.01f,.2f),rf(-.1f,.1f)};dc.residual_mean=(UbigStageBRtResidualMeanConfig){rf(.1f,.9f),rf(.1f,.9f),rf(.1f,.9f),rf(.1f,.9f)};dc.envelope=(UbigStageBRtEnvelopeConfig){rf(.1f,.9f),rf(.1f,.9f),rf(-.4f,0),rf(.1f,1),rf(.1f,1),rf(.01f,.2f),rf(-.1f,.1f),weights};dc.post_new=rf(.1f,.9f);dc.post_old=rf(.1f,.9f);
 UbigStageBRtDeepControllerControls ctrl={rf(.1f,1),rf(-.1f,.1f),rf(-.2f,.2f),rf(-.2f,.2f),rf(-.2f,.2f),rf(-.2f,.2f)};
 float filt[640],phase[128],curve[6],kernel[64];for(unsigned i=0;i<640;i++)filt[i]=rf(-.1f,.1f);for(unsigned i=0;i<128;i++)phase[i]=rf(-1,1);for(unsigned i=0;i<6;i++)curve[i]=rf(.05f,.95f);for(unsigned i=0;i<64;i++)kernel[i]=rf(0,1);UbigStageBRtLateControllerConfig lc={filt,phase,curve,kernel,rf(.005f,.1f),rf(.02f,.2f)};
 UbigStageBRtLatePipelineState st;memset(&st,0,sizeof st);st.deep.config=&dc;st.deep.mode=1;st.deep.row_count_cache=2;st.deep.dual.config=&dc.dual_envelope;st.deep.dual.active_width=20;st.deep.envelope.config=&dc.envelope;st.deep.envelope.active_width=20;st.deep.pair_bounds.config=&dc.pair_bounds;st.deep.pair_bounds.active_width=20;st.deep.residual_mean.config=&dc.residual_mean;st.deep.residual_mean.active_width=20;for(unsigned i=0;i<20;i++){st.deep.dual.primary[i]=rf(-1,1);st.deep.dual.secondary[i]=rf(-1,1);st.deep.envelope.envelope[i]=rf(-1,1);st.deep.envelope.lane_activity[i]=rf(-1,1);st.deep.intermediate[i]=rf(-1,1);st.deep.output[i]=rf(-1,1);}st.deep.envelope.scalar_envelope=rf(-1,1);st.deep.envelope.activity_state=rf(-1,1);st.deep.pair_bounds.baseline=rf(-.1f,.1f);st.deep.residual_mean.scalar=rf(-1,1);
 st.late.output=rf(-.05f,.05f);for(unsigned r=0;r<2;r++)for(unsigned i=0;i<576;i++)st.late.transform_history[r][i]=rf(-.05f,.05f);st.late.previous_peak=rf(0,.3f);st.late.delayed_envelope=rf(.2f,1);st.late.gain=rf(.2f,1);st.late.envelope=rf(.2f,1);st.late.smoothed=rf(.2f,1);st.late.history_scale=lc.history_scale;for(unsigned i=0;i<128;i++)st.late.history[i]=rf(-.05f,.05f);st.late.minimum_ring=rf(.2f,1);
 UbigStageBRtLatePipelineConfig cfg={0x1.7b63f2p-5f,ends,lower,upper,status,&ctrl,&lc};float late[2][256];for(unsigned r=0;r<2;r++)for(unsigned i=0;i<256;i++)late[r][i]=rf(-.05f,.05f);ubig_stage_b_rt_late_pipeline_process(rf(0,.06f),&st,&cfg,&groups,&analysis,&output,linked,bm,om,late);
 h=hh(h,obj,sizeof obj);h=hh(h,ai,sizeof ai);h=hh(h,ao,sizeof ao);h=hh(h,linked,sizeof linked);h=hh(h,bm,sizeof bm);h=hh(h,om,sizeof om);h=hh(h,late,sizeof late);h=hh(h,st.deep.dual.primary,sizeof st.deep.dual.primary);h=hh(h,st.deep.dual.secondary,sizeof st.deep.dual.secondary);h=hh(h,st.deep.envelope.envelope,sizeof st.deep.envelope.envelope);h=hh(h,st.deep.output,sizeof st.deep.output);h=hh(h,&st.late.output,sizeof st.late.output);h=hh(h,st.late.transform_history,sizeof st.late.transform_history);h=hh(h,st.late.history,sizeof st.late.history);h=hh(h,&st.late.minimum_ring,sizeof st.late.minimum_ring);
}
if(h!=0xd12a6d18bdef5fbaULL){fprintf(stderr,"Stage-B RT late-pipeline hash %016llx\n",(unsigned long long)h);return 2;}puts("PASS Stage-B RT late-pipeline regression");return 0;}
