wireplumber.components = [
  {
    name = "sp11-pulse-hide-hardware.lua"
    type = script/lua
    provides = custom.sp11-pulse-hide-hardware
  }
]

wireplumber.profiles = {
  main = {
    custom.sp11-pulse-hide-hardware = required
  }
}
