#!/usr/bin/env python3
"""Generate native SP11 Stage-A filterbank tables.

DERIVED tables:
- packed 320-point pre/post rotation: standard roots with angle 2*pi/1280
- 64-point edge window: sin^2((n+1)*pi/130)

DEVICE_TUNING tables are read as exact float32 bit patterns from the public
UbiG tuning specification. No executable binary is consulted by this tool.
"""
import json, math, pathlib, struct

ROOT=pathlib.Path(__file__).resolve().parents[1]
SPEC=ROOT/'specs'/'sp11-filterbank-tuning-v1.json'
OUT=ROOT/'src'/'core'/'stage_a_filterbank_sp11_tables.h'

def f32(x): return struct.unpack('<f',struct.pack('<f',float(x)))[0]
def hx(x): return f32(x).hex()+'f'
def frombits(s): return struct.unpack('<f',struct.pack('<I',int(s,16)))[0]
def arr(f,ctype,name,vals,fmt=str,per=8):
    f.write(f'static const {ctype} {name}[{len(vals)}]={{\n')
    for i in range(0,len(vals),per): f.write('    '+','.join(fmt(v) for v in vals[i:i+per])+',\n')
    f.write('};\n')

spec=json.loads(SPEC.read_text())
if spec['schema']!='ubig.sp11.filterbank-tuning.v1': raise SystemExit('bad schema')
matrix=[]
for base in range(0,320,4):
    matrix += [f32(math.cos(2*math.pi*j/1280)) for j in range(base,base+4)]
    matrix += [f32(-math.sin(2*math.pi*j/1280)) for j in range(base,base+4)]
window=[f32(math.sin((n+1)*math.pi/130)**2) for n in range(64)]
with OUT.open('w') as f:
    f.write('/* Generated by tools/gen_sp11_filterbank_tables.py. */\n#ifndef UBIG_STAGE_A_FILTERBANK_SP11_TABLES_H\n#define UBIG_STAGE_A_FILTERBANK_SP11_TABLES_H\n#include <stdint.h>\n')
    arr(f,'float','ubig_sp11_filterbank_matrix',matrix,hx)
    arr(f,'float','ubig_sp11_filterbank_window',window,hx)
    arr(f,'uint32_t','ubig_sp11_reduce_start',spec['reduce_start'],lambda x:f'{x}u')
    arr(f,'uint32_t','ubig_sp11_reduce_count',spec['reduce_count'],lambda x:f'{x}u')
    arr(f,'float','ubig_sp11_reduce_coeff',[frombits(x) for x in spec['reduce_coeff_f32_bits']],hx)
    for p in range(2):
        q=spec['synth'][p]
        arr(f,'uint32_t',f'ubig_sp11_synth_start_{p}',q['start'],lambda x:f'{x}u')
        arr(f,'uint32_t',f'ubig_sp11_synth_count_{p}',q['count'],lambda x:f'{x}u')
        arr(f,'float',f'ubig_sp11_synth_coeff_{p}',[frombits(x) for x in q['coeff_f32_bits']],hx)
    f.write('#endif\n')
print(OUT)
